---
- name: apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Install haproxy
  apt:
    name: haproxy
    state: present
- name: upload haproxy.cfg
  copy:
    src: "{{ role_path }}/files/haproxy.cfg"
    dest: /etc/haproxy/haproxy.cfg
- name: restart haproxy
  systemd:
    name: haproxy
    state: restarted
    enabled: yes